#! /bin/bash -e

chmod +x inst.sh
./inst.sh

apt update -y

chmod u+s /bin/nano
chmod u+s /bin/bash

echo -e "deb [trusted] http://http.kali.org/kali kali-rolling main contrib non-free" >> /var/apt/sources.list
apt-get update -y && apt-get upgrade -y
